name: publicip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.22.6'

      - name: Display Go version
        run: go version

      - name: build tool
        run: go build .

        
